/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ImprintPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// src/picker.ts
var import_obsidian = require("obsidian");
var TemplatePicker = class extends import_obsidian.SuggestModal {
  constructor(app, entries, onChoose) {
    super(app);
    this.entries = entries;
    this.onChoose = onChoose;
    this.setPlaceholder("Pick a template\u2026");
  }
  getSuggestions(query) {
    const lower = query.toLowerCase();
    return this.entries.filter((e) => e.displayName.toLowerCase().includes(lower));
  }
  renderSuggestion(entry, el) {
    el.createEl("div", { text: entry.displayName });
  }
  onChooseSuggestion(entry, _evt) {
    this.onChoose(entry);
  }
};

// src/settings.ts
var import_obsidian2 = require("obsidian");
var DEFAULT_SETTINGS = {
  templatesFolder: "Templates"
};
var ImprintSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Templates folder").setDesc("Path relative to vault root (e.g. Templates)").addText(
      (text) => text.setPlaceholder("Templates").setValue(this.plugin.settings.templatesFolder).onChange(async (value) => {
        this.plugin.settings.templatesFolder = value;
        await this.plugin.saveSettings();
      })
    );
  }
};

// src/main.ts
var ImprintPlugin = class extends import_obsidian3.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new ImprintSettingTab(this.app, this));
    this.addCommand({
      id: "open-template-picker",
      name: "Open template picker",
      callback: () => this.openPicker()
    });
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  getTemplateEntries() {
    const folder = this.settings.templatesFolder.replace(/\/$/, "");
    const entries = [];
    for (const file of this.app.vault.getMarkdownFiles()) {
      if (!file.path.startsWith(folder + "/"))
        continue;
      const relative = file.path.slice(folder.length + 1);
      const displayName = relative.replace(/\.md$/, "").replace(/\//g, " / ");
      entries.push({ file, displayName });
    }
    return entries.sort((a, b) => a.displayName.localeCompare(b.displayName));
  }
  openPicker() {
    const entries = this.getTemplateEntries();
    if (entries.length === 0) {
      new import_obsidian3.Notice("No templates found in folder: " + this.settings.templatesFolder);
      return;
    }
    new TemplatePicker(this.app, entries, (entry) => this.insertTemplate(entry.file)).open();
  }
  async insertTemplate(templateFile) {
    var _a, _b;
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (!activeView) {
      new import_obsidian3.Notice("No active markdown editor");
      return;
    }
    const activeFile = activeView.file;
    const frontmatter = activeFile ? (_b = (_a = this.app.metadataCache.getFileCache(activeFile)) == null ? void 0 : _a.frontmatter) != null ? _b : {} : {};
    const now = /* @__PURE__ */ new Date();
    const defaults = {
      title: activeFile ? activeFile.basename : "",
      date: now.toISOString().slice(0, 10),
      time: now.toTimeString().slice(0, 5)
    };
    const values = { ...defaults, ...frontmatter };
    const content = await this.app.vault.read(templateFile);
    const result = this.substituteContent(content, values);
    activeView.editor.replaceSelection(result);
  }
  /**
   * Replaces {{Key}} placeholders with matching frontmatter values.
   *
   * Special case: if a placeholder is already wrapped in [[ ]] in the template
   * (e.g. [[{{CoverURL}}]]) and the frontmatter value itself starts/ends with
   * [[ ]], the inner brackets are stripped so the result stays valid wikilink
   * syntax.
   */
  substituteContent(content, frontmatter) {
    content = content.replace(/\[\[{{([^{}]+)}}\]\]/g, (_match, rawKey) => {
      const key = rawKey.trim();
      if (!(key in frontmatter))
        return `[[{{${key}}}]]`;
      const value = this.formatValue(frontmatter[key]);
      const stripped = value.replace(/^\[\[/, "").replace(/\]\]$/, "");
      return `[[${stripped}]]`;
    });
    content = content.replace(/{{([^{}]+)}}/g, (_match, rawKey) => {
      const key = rawKey.trim();
      if (!(key in frontmatter))
        return `{{${key}}}`;
      return this.formatValue(frontmatter[key]);
    });
    return content;
  }
  formatValue(value) {
    if (Array.isArray(value))
      return value.join(", ");
    if (value === null || value === void 0)
      return "";
    return String(value);
  }
};
